services:
  db:
    image: postgres:16-alpine
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - cada_brand_pg:/var/lib/postgresql/data

volumes:
  cada_brand_pg:
